baseurl: "https://trackula.org/"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
title: "Trackula Blog"
canonifyurls: true

DefaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

xtheme: "beautifulhugo"
theme: "trackula"
enableGitInfo: true
metaDataFormat: "yaml"
pygmentsUseClasses: true
pygmentCodeFences: true

outputs:
home: ["HTML", "RSS"]
page: ["HTML", "JSON"]

languages:
  en:
    title: "Trackula"
    weight: 1
    languagecode: "en"
  es:
    title: "Trackula"
    weight: 2
    languagecode: "es"


Params:
  slogan: "Watching them watch us"
  logo: "img/avatar-icon.png"
  favicon: "img/favicon.ico"
  dateFormat: "2006-02-31"
  copyright: "This work is licensed under a Creative Commons Attribution 4.0 International license."
  license: https://creativecommons.org/licenses/by/4.0/
  commit: true
  rss: true
  comments: true
  languages: [en, es]
#  gcse: "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

  Social:
    twitter: "https://twitter.com/trackula_"
    github: "https://github.com/trackula"
    gitlab: "https://gitlab.com/trackula"
    
  Authors:
    ssaavedra:
      name: Santiago Saavedra
      nick: ssaavedra
      github: ssaavedra
      gitlab: mapcar
      twitter: ssice
    trackula:
      name: Asociaci√≥n Cultural Hacktivista Trackula
      nick: trackula
      github: trackula
      gitlab: trackula
      twitter: trackula_

#[[Params.bigimg]]
#  src: "img/triangle.jpg"
#  desc: "Triangle"
#[[Params.bigimg]]
#  src: "img/sphere.jpg"
#  desc: "Sphere"
#[[Params.bigimg]]
#  src: "img/hexagon.jpg"
#  desc: "Hexagon"

Author:
  name: "Some Person"
  email: "youremail@domain.com"
  facebook: "username"
  googleplus: "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab: "username"
  github: "username"
  twitter: "username"
  reddit: "username"
  linkedin: "username"
  xing: "username"
  stackoverflow: "users/XXXXXXX/username"
  snapchat: "username"
  instagram: "username"
  youtube: "user/username" # or channel/channelname
  soundcloud: "username"
  spotify: "username"
  bandcamp: "username"
  itchio: "username"


menus:
  main:
  - name: "Latest news"
    url: ""
    weight: 1
  - name: "Trackula for Web"
    url: "page/landing-plugin/"
    weight: 3
  - name: "About us"
    url: "page/about/"
    weight: 5
  - name: "Tags"
    url: "tags"
    weight: 6
